"""DROID world-model training config: bootstrap distractor v1, trained from
raw SVD (see below), reusing ``droid_flow_matching_uq_false_future_v3``'s
checkpoint only as the frozen bootstrap-future sampler.

v1-v3 of the false-future/UQ line (configs/training/droid_wm_uq_false_future_v3.py
and its own module docstring) already established that the history-future-overlap
peek + logvar-head self-consistency recipe COLLAPSES on DROID: the model learns
"peek present => more confident" regardless of whether the peek is the true
future, a temporally-shifted same-episode window (p_shifted_future), or an
unrelated other-episode window (p_false_future). Aggregating this project's own
on-disk replay-eval metrics (checkpoints/wm_droid/*/replay_epi_*/chunk_metrics.jsonl)
for false_future_v1 and v3 confirms this persists through v3's masking fix:
mean_epi_var_signed stays negative (v1: -0.112, v3: -0.112 at the latest
checkpoint, -0.076 at 120k) even though epi_full_latent_mse (the actual
prediction error on a false/shifted peek) is substantial (0.07-0.16) -- a
well-calibrated model should show INCREASED variance there, not decreased.

Suspected root cause: p_false_future/p_shifted_future distractors come from
unrelated data (a different episode, or a shifted time window), so the model
can key off cheap structural tells (e.g. does the peek look temporally/
action-consistent with this trajectory at all) rather than learning genuine
content-plausibility judgment -- it never has to seriously doubt a
plausible-LOOKING peek, because the distractors it's shown never look
plausible in the first place.

This config ports the "bootstrap" idea from
wm_uq/jobs/train_push_cube_bootstrap_unified_phaseA.sh + ...phaseB.sh: instead
of relying only on real-but-obviously-wrong distractors, add a THIRD
distractor type -- p_bootstrap_future -- that is a SELF-SAMPLED synthetic
future, generated by the model's own flow-matching sampler conditioned on
THIS episode's real history+actions (scripts/generate_bootstrap_futures_droid.py),
starting from pure noise. Unlike an other-episode/shifted-time distractor,
this looks like a genuine continuation of the trajectory being trained on --
but is only a stochastic sample, not guaranteed correct -- forcing the logvar
head to actually judge plausibility instead of detecting an episode/time
mismatch.

droid_flow_matching_uq_false_future_v3's checkpoint (checkpoint-220000.pt)
still serves as the frozen sampler that generated the bootstrap-future cache
(scripts/generate_bootstrap_futures_droid.py, independent of this file --
that script hardcodes its own --checkpoint and is unaffected by anything
below). This config itself, however, trains from raw SVD rather than
warm-starting from v3 (ckpt_path=None, matching v3's own from-scratch choice
-- see v3's module docstring on why warm-starting risks baking in a
pre-existing shortcut): the bootstrap distractor is a big enough change to
the training distribution (a fourth, harder content-plausibility negative
present from step 0) that isolating its effect is cleaner from a fresh run
than compounded on top of v3's own already-collapsed weights. This also
sidesteps needing to first establish whether v3's weights would adapt
cleanly to a distribution they never saw during their own training.

max_train_steps=220_000 matches v3's own actual trained duration (not its
500_000 configured budget) for an apples-to-apples step count between the
two runs.

Mixing scheme (conditional on p_history_future_overlap=0.5 firing, unchanged
from v3): p_shifted_future and p_false_future are each reduced from v3's
0.25 to 0.15 (kept nonzero -- an easy/hard distractor spectrum, and an
in-run baseline against the pre-bootstrap collapse behavior), and
p_bootstrap_future=0.40 takes the largest share of the reallocated budget
since it's the mechanism actually targeting the collapse. Implicit true-peek
share drops from v3's 0.50 to 0.30. bootstrap_cache_root can only ever hold
PARTIAL coverage of DROID's ~8.7M-sample train split, but dataset.py draws the
bootstrap-selected training example directly FROM the cached-anchor index
(built once in __init__) rather than drawing a row uniformly and checking it
for a cache hit -- so the realized p_bootstrap_future rate matches 0.40
exactly regardless of coverage fraction (it only falls back to the
other-episode distractor if the cache is entirely empty). This does mean
bootstrap-negative examples are drawn from a smaller pool of distinct
(episode, frame_now) anchors than the other distractor types -- scale up
anchors_per_episode (scripts/generate_bootstrap_futures_droid.py) if that
narrower anchor diversity turns out to matter for the eval signal.

Everything else (architecture, p_history_future_overlap, mask_history_from_peek,
zero_overlap_action, fixed_overlap_k, dataset, compute settings) is unchanged
from v3 -- this isolates the new distractor axis plus the from-scratch
restart as the only changes under test.

IMPORTANT -- eval/inference compatibility: same flags as v3
(--mask_history_from_peek --overlap_zero_action --epi_overlap_k 0), since
bootstrap only changes what the checkpoint saw as context DURING TRAINING,
never at eval time -- see jobs/replay_droid_wm_traj_epi_bootstrap_v1.sh.

Tag bumped to droid_flow_matching_uq_bootstrap_v1 so this run's checkpoints
land in a fresh directory instead of touching v3's.
"""

import os

from openworld.training.world_model.config import LiberoWMArgs


def get_args() -> LiberoWMArgs:
    data_root = "/scratch/gpfs/AM43/yy4041/data"
    args = LiberoWMArgs(
        # ----- Paths (set these to your installation) -----
        svd_model_path="external/stable-video-diffusion-img2vid",
        clip_model_path="external/clip-vit-base-patch32",
        # Train from raw SVD -- see module docstring for why this run does
        # NOT warm-start from v3 (unlike an earlier version of this config).
        ckpt_path=None,

        # ----- Dataset: reuse vidwm's existing droid_ctrl_world data -----
        dataset_root_path=data_root,
        dataset_meta_info_path=os.path.join(data_root, "dataset_meta_info"),
        dataset_names="droid_ctrl_world",
        dataset_cfgs="dataset_meta_info/droid_ctrl_world",
        prob=(1.0,),
        annotation_name="annotation",

        # ----- Compute (unchanged from v3) -----
        train_batch_size=3,
        gradient_accumulation_steps=2,
        mixed_precision="fp16",
        num_workers=4,

        # ----- Schedule -----
        learning_rate=1e-5,
        max_train_steps=220_000,  # matches v3's actual trained step count -- see module docstring
        checkpointing_steps=10_000,
        validation_steps=10_000,
        max_grad_norm=1.0,

        # ----- Architecture (DROID-specific: 3 cams, 192x320, unchanged from v3) -----
        num_cams=3,
        height=192,
        width=320,
        num_frames=5,
        num_history=6,
        action_dim=7,
        down_sample=3,

        # ----- Loss / sampling defaults -----
        flow_map_type="flow_matching",
        distance_conditioning=False,

        # ----- UQ head -----
        predict_uncertainty=True,
        uncertainty_weight=0.01,

        # ----- History-future-overlap augmentation (unchanged from v3) -----
        p_future_in_history=0.0,
        p_history_future_overlap=0.5,
        history_overlap_noise_scale=0.3,
        fixed_overlap_k=True,

        # ----- Three-way -> four-way future mix -----
        p_false_future=0.15,      # down from v3's 0.25 -- easy negative, reduced but retained
        p_shifted_future=0.15,    # down from v3's 0.25 -- easy negative, reduced but retained
        p_bootstrap_future=0.40,  # new -- hard, content-plausible negative; largest share
        bootstrap_cache_root="outputs/bootstrap_futures_cache_droid",
        zero_overlap_action=True,

        # ----- Fixed-length masked peek (unchanged from v3) -----
        mask_history_from_peek=True,

        tag="droid_flow_matching_uq_bootstrap_v1",
        wandb_project_name="droid_world_model",
    )
    # Override the config.py default of checkpoints/wm_libero/<tag> so DROID
    # runs don't land under a misleadingly-named "wm_libero" directory.
    args.output_dir = f"checkpoints/wm_droid/{args.tag}"
    return args
