"""DROID world-model training config: bootstrap distractor v1, on top of
``droid_flow_matching_uq_false_future_v3``.

v1-v3 of the false-future/UQ line (configs/training/droid_wm_uq_false_future_v3.py
and its own module docstring) already established that the history-future-overlap
peek + logvar-head self-consistency recipe COLLAPSES on DROID: the model learns
"peek present => more confident" regardless of whether the peek is the true
future, a temporally-shifted same-episode window (p_shifted_future), or an
unrelated other-episode window (p_false_future). Aggregating this project's own
on-disk replay-eval metrics (checkpoints/wm_droid/*/replay_epi_*/chunk_metrics.jsonl)
for false_future_v1 and v3 confirms this persists through v3's masking fix:
mean_epi_var_signed stays negative (v1: -0.112, v3: -0.112 at the latest
checkpoint, -0.076 at 120k) even though epi_full_latent_mse (the actual
prediction error on a false/shifted peek) is substantial (0.07-0.16) -- a
well-calibrated model should show INCREASED variance there, not decreased.

Suspected root cause: p_false_future/p_shifted_future distractors come from
unrelated data (a different episode, or a shifted time window), so the model
can key off cheap structural tells (e.g. does the peek look temporally/
action-consistent with this trajectory at all) rather than learning genuine
content-plausibility judgment -- it never has to seriously doubt a
plausible-LOOKING peek, because the distractors it's shown never look
plausible in the first place.

This config ports the "bootstrap" idea from
wm_uq/jobs/train_push_cube_bootstrap_unified_phaseA.sh + ...phaseB.sh: instead
of relying only on real-but-obviously-wrong distractors, add a THIRD
distractor type -- p_bootstrap_future -- that is a SELF-SAMPLED synthetic
future, generated by the model's own flow-matching sampler conditioned on
THIS episode's real history+actions (scripts/generate_bootstrap_futures_droid.py),
starting from pure noise. Unlike an other-episode/shifted-time distractor,
this looks like a genuine continuation of the trajectory being trained on --
but is only a stochastic sample, not guaranteed correct -- forcing the logvar
head to actually judge plausibility instead of detecting an episode/time
mismatch.

Unlike push_cube's Phase A (trained from scratch, ctx_mask_prob=1.0, purely
to serve as an unbiased frozen sampler), this config REUSES the existing
droid_flow_matching_uq_false_future_v3 checkpoint (checkpoint-220000.pt) as
BOTH the frozen sampler (see the generation script) AND the warm-start
weights for this run -- v3 already has the masked-peek architecture
(mask_history_from_peek=True) and reasonable DROID generation quality, so
there is no need to train a separate Phase-A-equivalent model from scratch
(confirmed decision -- saves ~220k steps of compute). This makes the run
effectively "Phase B only".

ckpt_path is a bare state_dict load (see train_wm.py) -- NOT a full resume:
global_step, optimizer state, and the LR schedule all restart from 0.
max_train_steps=40_000 (vs v3's 500_000 budget / 220k actual steps trained)
mirrors push_cube's Phase A -> Phase B step-budget ratio (100k -> 40k):
this run's checkpoint-40000.pt therefore represents 220k (v3) + 40k
(this run) = 260k real steps total, not 40k -- a bookkeeping point only,
since global_step itself starts at 0.

Mixing scheme (conditional on p_history_future_overlap=0.5 firing, unchanged
from v3): p_shifted_future and p_false_future are each reduced from v3's
0.25 to 0.15 (kept nonzero -- an easy/hard distractor spectrum, and an
in-run baseline against the pre-bootstrap collapse behavior), and
p_bootstrap_future=0.40 takes the largest share of the reallocated budget
since it's the mechanism actually targeting the collapse. Implicit true-peek
share drops from v3's 0.50 to 0.30. NOTE: because bootstrap_cache_root can
only ever hold PARTIAL coverage of DROID's ~8.7M-sample train split (dataset.py
falls back to the other-episode distractor on a cache miss), the REALIZED
p_bootstrap_future rate will be diluted below 0.40 by the cache miss rate --
scale up the cache's coverage fraction (scripts/generate_bootstrap_futures_droid.py)
if that dilution turns out to make the eval signal inconclusive.

Everything else (architecture, p_history_future_overlap, mask_history_from_peek,
zero_overlap_action, fixed_overlap_k, dataset, compute settings) is unchanged
from v3 -- this isolates the new distractor axis as the only change under
test, and keeps the warm start a clean continuation rather than a second
distribution shift on top of v3's own masking change.

IMPORTANT -- eval/inference compatibility: same flags as v3
(--mask_history_from_peek --overlap_zero_action --epi_overlap_k 0), since
bootstrap only changes what the checkpoint saw as context DURING TRAINING,
never at eval time -- see jobs/replay_droid_wm_traj_epi_bootstrap_v1.sh.

Tag bumped to droid_flow_matching_uq_bootstrap_v1 so this run's checkpoints
land in a fresh directory instead of touching v3's.
"""

import os

from openworld.training.world_model.config import LiberoWMArgs

_V3_CKPT_DIR = "checkpoints/wm_droid/droid_flow_matching_uq_false_future_v3"


def get_args() -> LiberoWMArgs:
    data_root = "/scratch/gpfs/AM43/yy4041/data"
    args = LiberoWMArgs(
        # ----- Paths (set these to your installation) -----
        svd_model_path="external/stable-video-diffusion-img2vid",
        clip_model_path="external/clip-vit-base-patch32",
        # Warm start from v3's final checkpoint -- bare state_dict load (see
        # train_wm.py), NOT a full resume. See module docstring re: v3 as
        # both frozen sampler and warm-start weights.
        ckpt_path=os.path.join(_V3_CKPT_DIR, "checkpoint-220000.pt"),

        # ----- Dataset: reuse vidwm's existing droid_ctrl_world data -----
        dataset_root_path=data_root,
        dataset_meta_info_path=os.path.join(data_root, "dataset_meta_info"),
        dataset_names="droid_ctrl_world",
        dataset_cfgs="dataset_meta_info/droid_ctrl_world",
        prob=(1.0,),
        annotation_name="annotation",

        # ----- Compute (unchanged from v3) -----
        train_batch_size=3,
        gradient_accumulation_steps=2,
        mixed_precision="fp16",
        num_workers=4,

        # ----- Schedule -----
        learning_rate=1e-5,
        max_train_steps=40_000,   # Phase-B-style reduced budget -- see module docstring
        checkpointing_steps=10_000,
        validation_steps=10_000,
        max_grad_norm=1.0,

        # ----- Architecture (DROID-specific: 3 cams, 192x320, unchanged from v3) -----
        num_cams=3,
        height=192,
        width=320,
        num_frames=5,
        num_history=6,
        action_dim=7,
        down_sample=3,

        # ----- Loss / sampling defaults -----
        flow_map_type="flow_matching",
        distance_conditioning=False,

        # ----- UQ head -----
        predict_uncertainty=True,
        uncertainty_weight=0.01,

        # ----- History-future-overlap augmentation (unchanged from v3) -----
        p_future_in_history=0.0,
        p_history_future_overlap=0.5,
        history_overlap_noise_scale=0.3,
        fixed_overlap_k=True,

        # ----- Three-way -> four-way future mix -----
        p_false_future=0.15,      # down from v3's 0.25 -- easy negative, reduced but retained
        p_shifted_future=0.15,    # down from v3's 0.25 -- easy negative, reduced but retained
        p_bootstrap_future=0.40,  # new -- hard, content-plausible negative; largest share
        bootstrap_cache_root="outputs/bootstrap_futures_cache_droid",
        zero_overlap_action=True,

        # ----- Fixed-length masked peek (unchanged from v3) -----
        mask_history_from_peek=True,

        tag="droid_flow_matching_uq_bootstrap_v1",
        wandb_project_name="droid_world_model",
    )
    # Override the config.py default of checkpoints/wm_libero/<tag> so DROID
    # runs don't land under a misleadingly-named "wm_libero" directory.
    args.output_dir = f"checkpoints/wm_droid/{args.tag}"
    return args
